# -*- coding: utf-8 -*-
##############################################################################
# Copyright (c) 2007, Timothy W. Cook and Contributors. All rights reserved.
# Redistribution and use are governed by the license in OSHIP-LICENSE.txt
#
# Use and/or redistribution of this file assumes you have read and accepted the
# terms of the license.
##############################################################################

"""

From the data types specification Rev 2.1.0

"""

__author__  = u'Timothy Cook <timothywayne.cook@gmail.com>'
__docformat__ = u'plaintext'

from zope.interface import implements 
from zope.i18nmessageid.message import MessageFactory 

from oship.openehr.rm.datatypes.basic.datavalue import DataValue
from interfaces.dvidentifier import IDvIdentifier

_ = MessageFactory('oship')   

class DvIdentifier(DataValue):
    """
    Type for representing identifiers of real-world entities. Typical identifiers include
    drivers licence number, social security number, vertans affairs number, prescrip-
    tion id, order id, and so on.
    DV_IDENTIFIER is used to represent any identifier of a real thing, issued by
    some authority or agency.
    DV_IDENTIFIER is not used to express identifiers generated by the infrastruc-
    ture to refer to information items; the types OBJECT_ID and OBJECT_REF and
    subtypes are defined for this purpose.
    """

    implements(IDvIdentifier)
    
    def __init__(self, issuer, assignor, id, type):
        if issuer != None and issuer != '':
            self.issuer=issuer
        else:
            raise AttributeError, "Invalid issuer value"
        
        if assignor != None and assignor != '':
            self.assignor=assignor
        else:
            raise AttributeError, "Invalid assignor value"
        
        if id != None and id != '':
            self.id=id
        else:
            raise AttributeError, "Invalid id value"

        if type != None and type != '':
            self.type=type
        else:
            raise AttributeError, "Invalid type value"
